### ISSUE TITLE
HEAD vs PING для проверки серверов

### ISSUE THREAD

**Issue by xboston** [metahashorg/metagate#13]
Сейчас #MetaGate проверяет доступность серверов отправляя им ping-запрос. Но если на сервере нода упала, или тормозит или вообще отсутсвует - то ping всё равно будет успешен. 
В то же время HEAD-запрос на нужный IP:POST выдаст более корректный результат и отобразит реальный статус доступности ноды/сервера.

Такая проверка требует времени не сильно больше чем ping, а результат надёжнее.

**Comment by magisterRab** [comment]
Работоспособность сервера проверяется посылкой post запроса на него

**Comment by xboston** [comment]
👍  ввело в заблуждение название ping-методов
