### ISSUE TITLE
#MetaGate not working

### ISSUE THREAD

**Issue by robertg1974** [metahashorg/metagate#16]
After update MetaGate not working.

![image](https://user-images.githubusercontent.com/27872021/63642582-88588080-c6c1-11e9-86c9-1e16ba6c2d52.png)

Log file
[log.1566444993101.txt](https://github.com/metahashorg/metagate/files/3537560/log.1566444993101.txt)

What can I do?

**Comment by magisterRab** [comment]
Try remove file 
C:/Users/ROBERT/.metagate/fill_nodes.txt

**Comment by robertg1974** [comment]
It works. Thanks
