### ISSUE TITLE
Antivirus Issue

### ISSUE THREAD

**Issue by amn357** [metahashorg/metagate#2]
Bitdefender: "The application metagate.exe accesses a web resource http://206.189.13.140:9999/  that has been detected as infected. The web resource has been successfully blocked and your PC is now safe."

This is BAD for Metahash no one will adopt until this is fixed. People dont want to hear "ignore it or Disable there antivirus".

Please Fix!

**Comment by SRaylyan** [comment]
Thank you for this report.

The IP address you specified above refers to one of our virtual machines. Most likely, earlier on this IP there was malware. Also you can scan by yourself (https://www.virustotal.com/) and make sure that only 1 antivirus out of 68 recognizes the link as malicious.
