### ISSUE TITLE
Обязательность опциональных полей при регистрации приложения

### ISSUE THREAD

**Issue by xboston** [metahashorg/metagate#8]
При регистрации приложения часть полей находится в блоке `optional`, но страница не отправляется если их не заполнить.

<img width="1248" alt="optional" src="https://user-images.githubusercontent.com/201306/54321258-536bdc00-4601-11e9-851f-7c4ccee7eec8.png">

**Comment by Nikitaempower** [comment]
Добрый день.

Эти поля являются обязательными для заполнения.

**Comment by xboston** [comment]
@Nikitaempower слово `Optional` смущает, вроде написано что необязательно - а по факту обязательно получается.

**Comment by xboston** [comment]
В текущей версии уже нет слова `Optional`, закрываю тикет
